[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  VITE_SIGNALING_MODE = "http"
  VITE_SIGNALING_HTTP_URL = "/.netlify/functions/signaling"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


